---
- name: Deploy web-site
  hosts: aghost
  gather_facts: no
  vars_prompt:
    - name: commit
      prompt: "What is the commit name?"
      private: no

  tasks:
    - name: webpack build for production
      delegate_to: localhost
      shell: webpack

    - name: git push
      delegate_to: localhost
      shell: git add -u && git add . && git commit -m "{{ commit }}" ; git push origin master

    - name: git pull
      shell: cd /home/tabula/denisbakhtin/projectmanager && git pull origin master

    - name: stop service
      shell: systemctl stop projectmanager
      become: yes

    - name: clean old binaries
      file:
        path: "{{ path }}"
        state: absent
      with_items: 
        - /home/tabula/denisbakhtin/projectmanager/projectmanager-go
        - /home/tabula/denisbakhtin/projectmanager/periodic-go

    - name: build new binary
      shell: cd /home/tabula/denisbakhtin/projectmanager && /home/tabula/golang/bin/go build -o projectmanager-go

    - name: build new periodic command binary
      shell: cd /home/tabula/denisbakhtin/projectmanager && /home/tabula/golang/bin/go build -o periodic-go cmd/periodical/main.go

    - name: start service
      shell: systemctl start projectmanager
      become: yes
